export const commonSchemas = {
  Source: {
    $id: 'Source',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      handle: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  // Custom Feed schemas
  CustomFeedFlags: {
    $id: 'CustomFeedFlags',
    type: 'object',
    nullable: true,
    properties: {
      name: { type: 'string', nullable: true },
      icon: { type: 'string', nullable: true },
      orderBy: {
        type: 'string',
        enum: ['DATE', 'UPVOTES', 'DOWNVOTES', 'COMMENTS', 'CLICKS'],
        nullable: true,
      },
      minDayRange: { type: 'integer', nullable: true },
      minUpvotes: { type: 'integer', nullable: true },
      minViews: { type: 'integer', nullable: true },
      disableEngagementFilter: { type: 'boolean', nullable: true },
    },
  },
  CustomFeed: {
    $id: 'CustomFeed',
    type: 'object',
    properties: {
      id: { type: 'string' },
      userId: { type: 'string', nullable: true },
      slug: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time', nullable: true },
      flags: { $ref: 'CustomFeedFlags#' },
    },
  },
  // Feed Settings schemas
  FeedAdvancedSettings: {
    $id: 'FeedAdvancedSettings',
    type: 'object',
    nullable: true,
    properties: {
      id: { type: 'integer' },
      enabled: { type: 'boolean' },
    },
  },
  FeedSettings: {
    $id: 'FeedSettings',
    type: 'object',
    properties: {
      id: { type: 'string', nullable: true },
      userId: { type: 'string', nullable: true },
      includeTags: {
        type: 'array',
        items: { type: 'string' },
        nullable: true,
      },
      blockedTags: {
        type: 'array',
        items: { type: 'string' },
        nullable: true,
      },
      includeSources: {
        type: 'array',
        items: { $ref: 'Source#' },
        nullable: true,
      },
      excludeSources: {
        type: 'array',
        items: { $ref: 'Source#' },
        nullable: true,
      },
      advancedSettings: {
        type: 'array',
        items: { $ref: 'FeedAdvancedSettings#' },
        nullable: true,
      },
    },
  },
  // Notification schemas
  NotificationAvatar: {
    $id: 'NotificationAvatar',
    type: 'object',
    properties: {
      referenceId: { type: 'string' },
      type: { type: 'string' },
      image: { type: 'string', nullable: true },
      name: { type: 'string' },
      targetUrl: { type: 'string', format: 'uri' },
    },
  },
  NotificationAttachment: {
    $id: 'NotificationAttachment',
    type: 'object',
    properties: {
      type: { type: 'string' },
      image: { type: 'string', nullable: true },
      title: { type: 'string' },
    },
  },
  Notification: {
    $id: 'Notification',
    type: 'object',
    properties: {
      id: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      readAt: { type: 'string', format: 'date-time', nullable: true },
      icon: { type: 'string' },
      title: { type: 'string' },
      type: { type: 'string' },
      description: { type: 'string', nullable: true },
      referenceId: { type: 'string' },
      targetUrl: { type: 'string', format: 'uri' },
      numTotalAvatars: { type: 'integer', nullable: true },
      avatars: {
        type: 'array',
        items: { $ref: 'NotificationAvatar#' },
        nullable: true,
      },
      attachments: {
        type: 'array',
        items: { $ref: 'NotificationAttachment#' },
        nullable: true,
      },
    },
  },
  UnreadCount: {
    $id: 'UnreadCount',
    type: 'object',
    properties: {
      count: { type: 'integer' },
    },
  },
  // Profile schemas
  SocialLink: {
    $id: 'SocialLink',
    type: 'object',
    properties: {
      platform: { type: 'string' },
      url: { type: 'string', format: 'uri' },
    },
  },
  UserLocation: {
    $id: 'UserLocation',
    type: 'object',
    nullable: true,
    properties: {
      city: { type: 'string', nullable: true },
      country: { type: 'string', nullable: true },
    },
  },
  Profile: {
    $id: 'Profile',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string', nullable: true },
      username: { type: 'string', nullable: true },
      bio: { type: 'string', nullable: true },
      readme: { type: 'string', nullable: true },
      readmeHtml: { type: 'string', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      cover: { type: 'string', format: 'uri', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      reputation: { type: 'integer' },
      permalink: { type: 'string', format: 'uri' },
      isPlus: { type: 'boolean', nullable: true },
      experienceLevel: { type: 'string', nullable: true },
      socialLinks: {
        type: 'array',
        items: { $ref: 'SocialLink#' },
      },
      location: { $ref: 'UserLocation#' },
    },
  },
  // Stack schemas
  Tool: {
    $id: 'Tool',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      faviconUrl: { type: 'string', format: 'uri', nullable: true },
    },
  },
  StackItem: {
    $id: 'StackItem',
    type: 'object',
    properties: {
      id: { type: 'string' },
      section: { type: 'string' },
      position: { type: 'integer' },
      startedAt: { type: 'string', format: 'date-time', nullable: true },
      icon: { type: 'string', nullable: true },
      title: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      tool: { $ref: 'Tool#' },
    },
  },
  // Simple success response
  SuccessResponse: {
    $id: 'SuccessResponse',
    type: 'object',
    properties: {
      success: { type: 'boolean' },
    },
  },
  Author: {
    $id: 'Author',
    type: 'object',
    nullable: true,
    properties: {
      name: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  AuthorWithId: {
    $id: 'AuthorWithId',
    type: 'object',
    nullable: true,
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
      username: { type: 'string', nullable: true },
    },
  },
  FeedPost: {
    $id: 'FeedPost',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri' },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      author: { $ref: 'Author#' },
    },
  },
  PostDetail: {
    $id: 'PostDetail',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      author: { $ref: 'AuthorWithId#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      bookmarked: { type: 'boolean' },
      userState: {
        type: 'object',
        nullable: true,
        properties: {
          vote: { type: 'integer' },
        },
      },
    },
  },
  Pagination: {
    $id: 'Pagination',
    type: 'object',
    properties: {
      hasNextPage: { type: 'boolean' },
      cursor: { type: 'string', nullable: true },
    },
  },
  Error: {
    $id: 'Error',
    type: 'object',
    properties: {
      error: { type: 'string' },
      message: { type: 'string' },
    },
  },
  RateLimitError: {
    $id: 'RateLimitError',
    type: 'object',
    properties: {
      error: { type: 'string' },
      message: { type: 'string' },
      retryAfter: { type: 'integer' },
    },
  },
  Tag: {
    $id: 'Tag',
    type: 'object',
    properties: {
      name: { type: 'string' },
    },
  },
  SourceSummary: {
    $id: 'SourceSummary',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      handle: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
      description: { type: 'string', nullable: true },
    },
  },
  BookmarkList: {
    $id: 'BookmarkList',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      icon: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
  },
  BookmarkedPost: {
    $id: 'BookmarkedPost',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri' },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      author: { $ref: 'Author#' },
      bookmarkedAt: { type: 'string', format: 'date-time' },
    },
  },
  CommentAuthor: {
    $id: 'CommentAuthor',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      username: { type: 'string', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      permalink: { type: 'string', format: 'uri' },
    },
  },
  CommentUserState: {
    $id: 'CommentUserState',
    type: 'object',
    nullable: true,
    properties: {
      vote: {
        type: 'integer',
        description: "User's vote on the comment (-1, 0, or 1)",
      },
    },
  },
  Comment: {
    $id: 'Comment',
    type: 'object',
    properties: {
      id: { type: 'string' },
      content: { type: 'string' },
      contentHtml: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      lastUpdatedAt: { type: 'string', format: 'date-time', nullable: true },
      permalink: { type: 'string', format: 'uri' },
      numUpvotes: { type: 'integer' },
      numAwards: {
        type: 'integer',
        description: 'Total number of awards on this comment',
      },
      author: { $ref: 'CommentAuthor#' },
      userState: { $ref: 'CommentUserState#' },
      children: {
        type: 'array',
        items: { $ref: 'Comment#' },
        description: 'Nested replies to this comment',
      },
    },
  },
  // User Experience schemas
  UserExperienceCompany: {
    $id: 'UserExperienceCompany',
    type: 'object',
    nullable: true,
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  UserExperienceCustomLocation: {
    $id: 'UserExperienceCustomLocation',
    type: 'object',
    nullable: true,
    properties: {
      city: { type: 'string', nullable: true },
      subdivision: { type: 'string', nullable: true },
      country: { type: 'string', nullable: true },
    },
  },
  UserExperienceSkill: {
    $id: 'UserExperienceSkill',
    type: 'object',
    properties: {
      value: { type: 'string' },
    },
  },
  UserExperienceRepository: {
    $id: 'UserExperienceRepository',
    type: 'object',
    nullable: true,
    properties: {
      id: { type: 'string', nullable: true },
      owner: { type: 'string', nullable: true },
      name: { type: 'string' },
      url: { type: 'string', format: 'uri' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  ProtoEnumValue: {
    $id: 'ProtoEnumValue',
    type: 'object',
    nullable: true,
    properties: {
      value: { type: 'string' },
    },
  },
  UserExperience: {
    $id: 'UserExperience',
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: {
        type: 'string',
        enum: [
          'work',
          'education',
          'project',
          'certification',
          'volunteering',
          'opensource',
        ],
      },
      title: { type: 'string' },
      subtitle: { type: 'string', nullable: true },
      grade: { type: 'string', nullable: true },
      description: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      startedAt: { type: 'string', format: 'date-time', nullable: true },
      endedAt: { type: 'string', format: 'date-time', nullable: true },
      customCompanyName: { type: 'string', nullable: true },
      customDomain: { type: 'string', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      employmentType: { $ref: 'ProtoEnumValue#' },
      locationType: { $ref: 'ProtoEnumValue#' },
      verified: { type: 'boolean', nullable: true },
      url: { type: 'string', format: 'uri', nullable: true },
      isOwner: { type: 'boolean', nullable: true },
      skills: {
        type: 'array',
        items: { $ref: 'UserExperienceSkill#' },
        nullable: true,
      },
      company: { $ref: 'UserExperienceCompany#' },
      customLocation: { $ref: 'UserExperienceCustomLocation#' },
      repository: { $ref: 'UserExperienceRepository#' },
    },
  },
};
