export const commonSchemas = {
  Source: {
    $id: 'Source',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      handle: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  Author: {
    $id: 'Author',
    type: 'object',
    nullable: true,
    properties: {
      name: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
    },
  },
  AuthorWithId: {
    $id: 'AuthorWithId',
    type: 'object',
    nullable: true,
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
      username: { type: 'string', nullable: true },
    },
  },
  FeedPost: {
    $id: 'FeedPost',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri' },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      author: { $ref: 'Author#' },
    },
  },
  PostDetail: {
    $id: 'PostDetail',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      author: { $ref: 'AuthorWithId#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      bookmarked: { type: 'boolean' },
      userState: {
        type: 'object',
        nullable: true,
        properties: {
          vote: { type: 'integer' },
        },
      },
    },
  },
  Pagination: {
    $id: 'Pagination',
    type: 'object',
    properties: {
      hasNextPage: { type: 'boolean' },
      cursor: { type: 'string', nullable: true },
    },
  },
  Error: {
    $id: 'Error',
    type: 'object',
    properties: {
      error: { type: 'string' },
      message: { type: 'string' },
    },
  },
  RateLimitError: {
    $id: 'RateLimitError',
    type: 'object',
    properties: {
      error: { type: 'string' },
      message: { type: 'string' },
      retryAfter: { type: 'integer' },
    },
  },
  Tag: {
    $id: 'Tag',
    type: 'object',
    properties: {
      name: { type: 'string' },
    },
  },
  SourceSummary: {
    $id: 'SourceSummary',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      handle: { type: 'string' },
      image: { type: 'string', format: 'uri', nullable: true },
      description: { type: 'string', nullable: true },
    },
  },
  BookmarkList: {
    $id: 'BookmarkList',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      icon: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
  },
  BookmarkedPost: {
    $id: 'BookmarkedPost',
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      url: { type: 'string', format: 'uri' },
      image: { type: 'string', format: 'uri', nullable: true },
      summary: { type: 'string', nullable: true },
      type: { type: 'string', description: 'Post type (article, share, etc.)' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      commentsPermalink: { type: 'string', format: 'uri' },
      source: { $ref: 'Source#' },
      tags: { type: 'array', items: { type: 'string' } },
      readTime: { type: 'integer', nullable: true },
      numUpvotes: { type: 'integer' },
      numComments: { type: 'integer' },
      author: { $ref: 'Author#' },
      bookmarkedAt: { type: 'string', format: 'date-time' },
    },
  },
  CommentAuthor: {
    $id: 'CommentAuthor',
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      username: { type: 'string', nullable: true },
      image: { type: 'string', format: 'uri', nullable: true },
      permalink: { type: 'string', format: 'uri' },
    },
  },
  CommentUserState: {
    $id: 'CommentUserState',
    type: 'object',
    nullable: true,
    properties: {
      vote: {
        type: 'integer',
        description: "User's vote on the comment (-1, 0, or 1)",
      },
    },
  },
  Comment: {
    $id: 'Comment',
    type: 'object',
    properties: {
      id: { type: 'string' },
      content: { type: 'string' },
      contentHtml: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      lastUpdatedAt: { type: 'string', format: 'date-time', nullable: true },
      permalink: { type: 'string', format: 'uri' },
      numUpvotes: { type: 'integer' },
      numAwards: {
        type: 'integer',
        description: 'Total number of awards on this comment',
      },
      author: { $ref: 'CommentAuthor#' },
      userState: { $ref: 'CommentUserState#' },
      children: {
        type: 'array',
        items: { $ref: 'Comment#' },
        description: 'Nested replies to this comment',
      },
    },
  },
};
