steps:
- name: node:10.12.0
  entrypoint: 'yarn'
  args: ['install']
- name: 'docker/compose:1.22.0'
  args: ['up', '-d']
- name: 'docker/compose:1.22.0'
  args: ['run', 'wait']
- name: node:10.12.0
  entrypoint: 'yarn'
  args: ['test']
  env:
  - MYSQL_HOST=mysql
  - MYSQL_USER=root
  - MYSQL_PASSWORD=12345
  - MYSQL_DATABASE=test
  - NODE_ENV=test
  - ADMIN_KEY=12345
  - DEFAULT_IMAGE_URL=https://cdn.com/image
  - DEFAULT_IMAGE_RATIO=1.2
  - DEFAULT_IMAGE_PLACEHOLDER=data:image/png;base64,asddasdqw
  secretEnv: ['SLACK_WEBHOOK']
- name: node:10.12.0
  entrypoint: 'yarn'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./helm/values/prod.yaml.enc
  - --plaintext-file=./helm/values/prod.yaml
  - --location=global
  - --keyring=daily-ci
  - --key=daily-api-ci
- name: 'gcr.io/$PROJECT_ID/helm'
  entrypoint: 'bash'
  args: ['-c', '([[ "$BRANCH_NAME" == "master" ]] && /builder/helm.bash upgrade daily-api ./helm/daily-api --namespace daily -f ./helm/values/prod.yaml --set-string image.tag=$SHORT_SHA,image.repository=gcr.io/$PROJECT_ID/$REPO_NAME -i) || ([[ "$BRANCH_NAME" != "master" ]] && echo "Skipping...")']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
  - 'GCLOUD_PROJECT=devkit-prod'

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

secrets:
- kmsKeyName: projects/daily-ops/locations/global/keyRings/daily-ci/cryptoKeys/daily-api-ci
  secretEnv:
    SLACK_WEBHOOK: "CiQA4mdVwsQrCLnNuXW+vtn46vuCLTwG0MwaSyDWsYk6HLrGPikSdgDpyKhXmF+YRgzIImIatRppR0qOLqg7YSLHv3A+BORSU7SmArWBVqXcScEF8IiV2fBTU7C5d5xuK0uSHHO4vBAugtZkUicfRMyFafi0fb7nhFHyZTTX+Y3sdTTMbhaTXpxBkSaZ3AWHRf8cpNCMlSRPUQXl+kI="
