FROM node:18-alpine
RUN apk add g++ make python3

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY .npmrc .
COPY package.json .
COPY package-lock.json .

RUN npm i -g nodemon
RUN npm i

COPY . .

CMD ["npm", "run", "dev"]

