export const NO_AI_BLOCKED_TAGS = [
  'ai',
  'machine-learning',
  'data-science',
  'llm',
  'deep-learning',
  'nlp',
  'genai',
  'openai',
  'chatgpt',
  'computer-vision',
  'ai-agents',
  'neural-networks',
  'pytorch',
  'tensorflow',
  'rag',
  'reinforcement-learning',
  'transformers',
  'prompt-engineering',
  'claude',
  'gpt',
  'vector-search',
  'anthropic',
  'google-gemini',
  'conversational-ai',
  'langchain',
  'mlops',
  'ai-coding',
  'ai-safety',
  'ai-security',
  'embeddings',
  'scikit',
  'aiops',
  'ai-assisted-development',
  'keras',
  'prompt-injection',
  'claude-code',
  'llama',
  'responsible-ai',
  'agentic-ai',
  'stable-diffusion',
  'huggingface',
  'vertex-ai',
  'ollama',
  'unsupervised-learning',
  'bert',
  'text-to-speech',
  'ai-governance',
  'ai-infrastructure',
  'text-generation',
  'midjourney',
  'vibe-coding',
  'diffusion-models',
  'deepseek',
  'mistral-ai',
  'grok',
  'explainable-ai',
  'ai-regulation',
  'google-ai',
  'vllm',
  'spring-ai',
  'ai-inference',
  'voice-ai',
  'stability-ai',
  'perplexity',
  'weaviate',
  'brain-computer-interface',
  'microsoft-copilot',
  'generative-art',
  'azure-openai',
  'dalle',
  'cohere',
  'edge-ai',
  'sora',
  'amazon-q',
  'llmops',
  'ai-engineering',
  'pinecone',
  'gemma',
  'local-ai',
  'azure-ai',
  'windsurf',
  'gpt-store',
  'codewhisperer',
  'duet-ai',
] as const;

export const NO_AI_BLOCKED_WORDS = [
  'AI',
  'A.I.',
  'token',
  'tokens',
  'ChatGPT',
  'GPT',
  'GPT-4',
  'GPT-5',
  'OpenAI',
  'Claude',
  'Claude Code',
  'Anthropic',
  'Gemini',
  'Copilot',
  'DeepSeek',
  'Mistral',
  'LLaMA',
  'Llama',
  'Ollama',
  'Qwen',
  'Mixtral',
  'Groq',
  'Cohere',
  'Codex',
  'DALL-E',
  'Sora',
  'Midjourney',
  'Stable Diffusion',
  'Gemma',
  'MiniMax',
  'Cursor',
  'Windsurf',
  'Devin',
  'Tabnine',
  'Codeium',
  'Supermaven',
  'LangChain',
  'LangSmith',
  'HuggingFace',
  'Hugging Face',
  'vLLM',
  'Perplexity',
  'Pinecone',
  'Weaviate',
  'LLM',
  'GenAI',
  'AGI',
  'NLP',
  'RAG',
  'AI agent',
  'AI agents',
  'agentic',
  'vibe coding',
  'vibe-coding',
  'machine learning',
  'deep learning',
  'neural network',
  'fine-tuning',
  'fine-tune',
  'embeddings',
  'transformer',
  'diffusion model',
  'prompt engineering',
  'prompt injection',
  'inference',
  'AI coding',
  'AI code',
  'AI-generated',
  'AI-powered',
  'AI-driven',
  'AI-assisted',
  'AI tool',
  'AI tools',
  'AI model',
  'AI models',
  'AI safety',
  'AI security',
  'AI governance',
  'AI regulation',
  'Dario Amodei',
  'Sam Altman',
  'Jensen Huang',
  'Elon Musk',
  'xAI',
] as const;
